### PR TITLE
Updated Labels Tooltip Level + Added Label Hover Related Callback

### PR DESCRIPTION
**Pull request by OssamaRafique**
Updated code to add tooltip to root body level to avoid css positioning issues. Along with that added hover and unhover callbacks.

### CODE REVIEW

**Comment by zoecastillo** [comment]
This looks fine to me. But, probably best to test in schub to see if the issues are resolved.

**Comment by OssamaRafique** [comment]
> This looks fine to me. But, probably best to test in schub to see if the issues are resolved.

Hi, Already tested. Works fine for me.

**Comment by jkanche** [comment]
can you add documentation to the README for hover and unhover callbacks?

**Comment by OssamaRafique** [comment]
> can you add documentation to the README for hover and unhover callbacks?

@jkanche Updated

**Comment by jkanche** [comment]
thanks, feel free to merge

**Pull request merged**
