### PR TITLE
Grouping Bars and Labels for Rows and Columns

### LINKED ISSUE #2: add grouping bars for each of the labels

### PR DESCRIPTION
**Pull request by OssamaRafique**
# Grouping Bars and Labels for Rows and Columns

This feature allows users to add grouping bars and labels to both rows and columns of the heatmap. It provides a convenient way to visually represent different groups in your heatmap data.

image

## Usage

You can use this feature by providing `groupingRowData` and `groupingColumnData` in your heatmap configuration. Both of these properties accept an array of objects, where each object represents a group and has the following properties:
- startIndex: The start index of the group in the data.
- endIndex: The end index of the group in the data.
- color: The color of the group bar.
- label: The label of the group.

Here's an example of how you can define your group data:

```const groups = [
  {
    startIndex: 0,
    endIndex: 1,
    color: "#52bc9a",
    label: "group 1",
  },
  // Additional groups...
];
```

Once the data is constructed, pass it to the library using the setState function:

```
plot.setState({
      groupingRowData,
      groupingColumnData
});
```

By default, the grouping color legends will be added inside the main DOM element, and the graph and x,y labels will be auto adjusted. There will be no labels for groups. However, users can hover over the legends to see the group name on the tooltip. You can customize this behaviour with the help of the setRowGroupingLegendOptions and setColumnGroupingLegendOptions methods.

```
plot.setRowGroupingLegendOptions("left", null, ".grouping-labels-rows", "vertical");
plot.setColumnGroupingLegendOptions("top", ".grouping-color-bar", ".grouping-labels-columns");
```

The first argument represents the positioning. For rows, it can be either "left" or "right". For columns, it can be either "top" or "bottom".

The second argument is a DOM element reference for grouping color bars in case you want it to be rendered somewhere else in the DOM. You can also pass null if you wish to keep the default behaviour.

The third argument is for grouping labels. As mentioned earlier, by default there will be no labels for groups. Group names will be visible via tooltip by default. If you wish to render them, you must provide the DOM element to render it to. The third argument represents the DOM element for it.

The fourth argument represents the orientation of labels. If you want to place them vertically from top to bottom or horizontally. This is optional. By default for rows, it will be vertical, and for columns, it will be horizontal.

### CODE REVIEW

**Comment by jkanche** [comment]
looks good to me, but also confirm with Janina tomorrow.

**Comment by zoecastillo** [comment]
It does look good to me too.

One question: in case we wanted to use a non-clustered heatmap where the groups are shuffled, i.e. not along consecutive columns or rows, would this setup allow adding them by re-using the same label? We would not want to create new colors or legend entries in this case, but ensure that the same label gets assigned to the same color every time it occurs.

**Comment by OssamaRafique** [comment]
> It does look good to me too.
> 
> One question: in case we wanted to use a non-clustered heatmap where the groups are shuffled, i.e. not along consecutive columns or rows, would this setup allow adding them by re-using the same label? We would not want to create new colors or legend entries in this case, but ensure that the same label gets assigned to the same color every time it occurs.

Yes the current setup supports non consecutive columns and rows that belong to same group. All we have to do it, create a new group with same color and label. Technically the group will be different but since name and colors would be same to users won't notice.

**Review by zoecastillo — APPROVED** [review]

**Comment by jkanche** [comment]
@OssamaRafique needs a version bump for the library

**Pull request merged**
