### PR TITLE
Adapting Hardcoded Data Normalization to Dynamic Ranges in Visualization

### PR DESCRIPTION
**Pull request by OssamaRafique**
Enhanced the script from a hardcoded normalization range of -1 to 1 to a dynamic approach based on user-defined maximum ranges. Initially designed for data visualization with fixed range normalization, it now flexibly normalizes row and column grouping data relative to specified maximum X and Y ranges. The function renders a row grouping legend in SVG, accurately adapting to both the entire data scope and the specific segment currently visible, ensuring a more versatile and accurate graphical representation.

### CODE REVIEW

**Comment by zoecastillo** [comment]
This looks good to me. 
Is there a reason why we are only doing this for TickPlot? Or any concern around the null values in BaseGL (I assume that is only a type of interface/abstract class that is not instantiated)?

**Review by zoecastillo — APPROVED** [review]

**Comment by OssamaRafique** [comment]
> This looks good to me. Is there a reason why we are only doing this for TickPlot? Or any concern around the null values in BaseGL (I assume that is only a type of interface/abstract class that is not instantiated)?

Thanks for the review. You're correct about the baseGL class. Since it is abstract class on which these plot are based of. I wanted to add a variable just for documentation purposes so later in future we know there are variables in base class that we can use to get the ranges.

To the second point, no we're not doing this only for Tickplot. I've done this for all 3 plots. Dot, Tick and Rect.

**Comment by zoecastillo** [comment]
Yes, but the range is fixed to [-1,1] for Dotplot and Rect, no?

**Comment by OssamaRafique** [comment]
> Yes, but the range is fixed to [-1,1] for Dotplot and Rect, no?

Correct,

For dotplot I updated the code and made it dynamic. But for rect plot since track type is categorical so epiviz.gl works with -1, 1 range. So any plot that will be based of rectGL (epiviz.heatmap.gl) will have this range.

In perturb-seq.gl we are overriding the generateSpec function that uses quantitative track type, there we will update the xAxisRange, or yAxisRange to use it later.
One thing I am planning to do later is, to make the track type quantitative in RectPlotGL and add the support for custom additions so we don't have to override the entire function.

**Pull request merged**
